name: utilities-stack

networks:
    default:
        name: home-net
        external: true

services:
    bentopdf:
        image: bentopdf/bentopdf:latest
        container_name: bentopdf
        volumes:
            - ./bentopdf:/data
        ports:
            - 3000:8080
        restart: unless-stopped

    omni-tools:
        image: iib0011/omni-tools:latest
        container_name: omni-tools
        volumes:
            - ./omni-tools:/data
        ports:
            - 8085:80
        restart: unless-stopped
